name: CI

on:
  pull_request:
    branches: [master]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3

      - name: install node deps
        run: yarn --frozen-lockfile

      - name: run tests
        run: yarn test
